/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\GyanTrika Labs\public\assets\gyantrika_innovation_hub.glb -o src/components/InnovationHub3D/Model.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    geometry_0: THREE.Mesh
    geometry_1: THREE.Mesh
    geometry_2: THREE.Mesh
    geometry_3: THREE.Mesh
    geometry_4: THREE.Mesh
    geometry_5: THREE.Mesh
    geometry_6: THREE.Mesh
    geometry_7: THREE.Mesh
    geometry_8: THREE.Mesh
    geometry_9: THREE.Mesh
    geometry_10: THREE.Mesh
    geometry_11: THREE.Mesh
    geometry_12: THREE.Mesh
    geometry_13: THREE.Mesh
    geometry_14: THREE.Mesh
    geometry_15: THREE.Mesh
    geometry_16: THREE.Mesh
    geometry_17: THREE.Mesh
    geometry_18: THREE.Mesh
    geometry_19: THREE.Mesh
    geometry_20: THREE.Mesh
    geometry_21: THREE.Mesh
    geometry_22: THREE.Mesh
    geometry_23: THREE.Mesh
    geometry_24: THREE.Mesh
    geometry_25: THREE.Mesh
    geometry_26: THREE.Mesh
    geometry_27: THREE.Mesh
    geometry_28: THREE.Mesh
    geometry_29: THREE.Mesh
    geometry_30: THREE.Mesh
    geometry_31: THREE.Mesh
    geometry_32: THREE.Mesh
    geometry_33: THREE.Mesh
    geometry_34: THREE.Mesh
    geometry_35: THREE.Mesh
    geometry_36: THREE.Mesh
    geometry_37: THREE.Mesh
    geometry_38: THREE.Mesh
    geometry_39: THREE.Mesh
    geometry_40: THREE.Mesh
    geometry_41: THREE.Mesh
    geometry_42: THREE.Mesh
    geometry_43: THREE.Mesh
    geometry_44: THREE.Mesh
    geometry_45: THREE.Mesh
    geometry_46: THREE.Mesh
    geometry_47: THREE.Mesh
    geometry_48: THREE.Mesh
    geometry_49: THREE.Mesh
    geometry_50: THREE.Mesh
    geometry_51: THREE.Mesh
    geometry_52: THREE.Mesh
    geometry_53: THREE.Mesh
    geometry_54: THREE.Mesh
    geometry_55: THREE.Mesh
    geometry_56: THREE.Mesh
    geometry_57: THREE.Mesh
    geometry_58: THREE.Mesh
    geometry_59: THREE.Mesh
    geometry_60: THREE.Mesh
    geometry_61: THREE.Mesh
    geometry_62: THREE.Mesh
    geometry_63: THREE.Mesh
    geometry_64: THREE.Mesh
    geometry_65: THREE.Mesh
    geometry_66: THREE.Mesh
    geometry_67: THREE.Mesh
    geometry_68: THREE.Mesh
    geometry_69: THREE.Mesh
    geometry_70: THREE.Mesh
    geometry_71: THREE.Mesh
    geometry_72: THREE.Mesh
    geometry_73: THREE.Mesh
    geometry_74: THREE.Mesh
    geometry_75: THREE.Mesh
    geometry_76: THREE.Mesh
    geometry_77: THREE.Mesh
    geometry_78: THREE.Mesh
    geometry_79: THREE.Mesh
    geometry_80: THREE.Mesh
    geometry_81: THREE.Mesh
    geometry_82: THREE.Mesh
    geometry_83: THREE.Mesh
    geometry_84: THREE.Mesh
    geometry_85: THREE.Mesh
    geometry_86: THREE.Mesh
    geometry_87: THREE.Mesh
    geometry_88: THREE.Mesh
    geometry_89: THREE.Mesh
    geometry_90: THREE.Mesh
    geometry_91: THREE.Mesh
    geometry_92: THREE.Mesh
    geometry_93: THREE.Mesh
    geometry_94: THREE.Mesh
    geometry_95: THREE.Mesh
    geometry_96: THREE.Mesh
    geometry_97: THREE.Mesh
    geometry_98: THREE.Mesh
    geometry_99: THREE.Mesh
    geometry_100: THREE.Mesh
    geometry_101: THREE.Mesh
    geometry_102: THREE.Mesh
    geometry_103: THREE.Mesh
    geometry_104: THREE.Mesh
    geometry_105: THREE.Mesh
    geometry_106: THREE.Mesh
    geometry_107: THREE.Mesh
    geometry_108: THREE.Mesh
    geometry_109: THREE.Mesh
    geometry_110: THREE.Mesh
    geometry_111: THREE.Mesh
    geometry_112: THREE.Mesh
    geometry_113: THREE.Mesh
    geometry_114: THREE.Mesh
    geometry_115: THREE.Mesh
    geometry_116: THREE.Mesh
    geometry_117: THREE.Mesh
    geometry_118: THREE.Mesh
    geometry_119: THREE.Mesh
    geometry_120: THREE.Mesh
    geometry_121: THREE.Mesh
    geometry_122: THREE.Mesh
    geometry_123: THREE.Mesh
    geometry_124: THREE.Mesh
    geometry_125: THREE.Mesh
    geometry_126: THREE.Mesh
    geometry_127: THREE.Mesh
    geometry_128: THREE.Mesh
    geometry_129: THREE.Mesh
    geometry_130: THREE.Mesh
    geometry_131: THREE.Mesh
    geometry_132: THREE.Mesh
    geometry_133: THREE.Mesh
    geometry_134: THREE.Mesh
    geometry_135: THREE.Mesh
    geometry_136: THREE.Mesh
    geometry_137: THREE.Mesh
    geometry_138: THREE.Mesh
    geometry_139: THREE.Mesh
    geometry_140: THREE.Mesh
    geometry_141: THREE.Mesh
    geometry_142: THREE.Mesh
    geometry_143: THREE.Mesh
    geometry_144: THREE.Mesh
    geometry_145: THREE.Mesh
    geometry_146: THREE.Mesh
    geometry_147: THREE.Mesh
    geometry_148: THREE.Mesh
    geometry_149: THREE.Mesh
    geometry_150: THREE.Mesh
    geometry_151: THREE.Mesh
    geometry_152: THREE.Mesh
    geometry_153: THREE.Mesh
    geometry_154: THREE.Mesh
    geometry_155: THREE.Mesh
    geometry_156: THREE.Mesh
    geometry_157: THREE.Mesh
    geometry_158: THREE.Mesh
    geometry_159: THREE.Mesh
    geometry_160: THREE.Mesh
    geometry_161: THREE.Mesh
    geometry_162: THREE.Mesh
    geometry_163: THREE.Mesh
    geometry_164: THREE.Mesh
    geometry_165: THREE.Mesh
    geometry_166: THREE.Mesh
    geometry_167: THREE.Mesh
    geometry_168: THREE.Mesh
    geometry_169: THREE.Mesh
    geometry_170: THREE.Mesh
    geometry_171: THREE.Mesh
    geometry_172: THREE.Mesh
    geometry_173: THREE.Mesh
    geometry_174: THREE.Mesh
    geometry_175: THREE.Mesh
    geometry_176: THREE.Mesh
    geometry_177: THREE.Mesh
    geometry_178: THREE.Mesh
    geometry_179: THREE.Mesh
    geometry_180: THREE.Mesh
    geometry_181: THREE.Mesh
    geometry_182: THREE.Mesh
    geometry_183: THREE.Mesh
    geometry_184: THREE.Mesh
    geometry_185: THREE.Mesh
    geometry_186: THREE.Mesh
    geometry_187: THREE.Mesh
    geometry_188: THREE.Mesh
    geometry_189: THREE.Mesh
    geometry_190: THREE.Mesh
    geometry_191: THREE.Mesh
    geometry_192: THREE.Mesh
    geometry_193: THREE.Mesh
    geometry_194: THREE.Mesh
    geometry_195: THREE.Mesh
    geometry_196: THREE.Mesh
    geometry_197: THREE.Mesh
    geometry_198: THREE.Mesh
    geometry_199: THREE.Mesh
    geometry_200: THREE.Mesh
    geometry_201: THREE.Mesh
    geometry_202: THREE.Mesh
    geometry_203: THREE.Mesh
    geometry_204: THREE.Mesh
    geometry_205: THREE.Mesh
    geometry_206: THREE.Mesh
    geometry_207: THREE.Mesh
    geometry_208: THREE.Mesh
    geometry_209: THREE.Mesh
    geometry_210: THREE.Mesh
    geometry_211: THREE.Mesh
    geometry_212: THREE.Mesh
    geometry_213: THREE.Mesh
    geometry_214: THREE.Mesh
    geometry_215: THREE.Mesh
    geometry_216: THREE.Mesh
    geometry_217: THREE.Mesh
    geometry_218: THREE.Mesh
    geometry_219: THREE.Mesh
    geometry_220: THREE.Mesh
    geometry_221: THREE.Mesh
    geometry_222: THREE.Mesh
    geometry_223: THREE.Mesh
    geometry_224: THREE.Mesh
    geometry_225: THREE.Mesh
    geometry_226: THREE.Mesh
    geometry_227: THREE.Mesh
    geometry_228: THREE.Mesh
    geometry_229: THREE.Mesh
    geometry_230: THREE.Mesh
    geometry_231: THREE.Mesh
    geometry_232: THREE.Mesh
    geometry_233: THREE.Mesh
    geometry_234: THREE.Mesh
    geometry_235: THREE.Mesh
    geometry_236: THREE.Mesh
    geometry_237: THREE.Mesh
    geometry_238: THREE.Mesh
    geometry_239: THREE.Mesh
    geometry_240: THREE.Mesh
    geometry_241: THREE.Mesh
    geometry_242: THREE.Mesh
    geometry_243: THREE.Mesh
    geometry_244: THREE.Mesh
    geometry_245: THREE.Mesh
    geometry_246: THREE.Mesh
    geometry_247: THREE.Mesh
    geometry_248: THREE.Mesh
    geometry_249: THREE.Mesh
    geometry_250: THREE.Mesh
    geometry_251: THREE.Mesh
    geometry_252: THREE.Mesh
    geometry_253: THREE.Mesh
    geometry_254: THREE.Mesh
    geometry_255: THREE.Mesh
    geometry_256: THREE.Mesh
    geometry_257: THREE.Mesh
    geometry_258: THREE.Mesh
    geometry_259: THREE.Mesh
    geometry_260: THREE.Mesh
    geometry_261: THREE.Mesh
    geometry_262: THREE.Mesh
    geometry_263: THREE.Mesh
    geometry_264: THREE.Mesh
    geometry_265: THREE.Mesh
    geometry_266: THREE.Mesh
    geometry_267: THREE.Mesh
    geometry_268: THREE.Mesh
    geometry_269: THREE.Mesh
    geometry_270: THREE.Mesh
    geometry_271: THREE.Mesh
    geometry_272: THREE.Mesh
    geometry_273: THREE.Mesh
    geometry_274: THREE.Mesh
    geometry_275: THREE.Mesh
    geometry_276: THREE.Mesh
    geometry_277: THREE.Mesh
    geometry_278: THREE.Mesh
    geometry_279: THREE.Mesh
    geometry_280: THREE.Mesh
    geometry_281: THREE.Mesh
    geometry_282: THREE.Mesh
    geometry_283: THREE.Mesh
    geometry_284: THREE.Mesh
    geometry_285: THREE.Mesh
    geometry_286: THREE.Mesh
    geometry_287: THREE.Mesh
    geometry_288: THREE.Mesh
    geometry_289: THREE.Mesh
    geometry_290: THREE.Mesh
    geometry_291: THREE.Mesh
    geometry_292: THREE.Mesh
    geometry_293: THREE.Mesh
    geometry_294: THREE.Mesh
    geometry_295: THREE.Mesh
    geometry_296: THREE.Mesh
    geometry_297: THREE.Mesh
    geometry_298: THREE.Mesh
    geometry_299: THREE.Mesh
    geometry_300: THREE.Mesh
    geometry_301: THREE.Mesh
    geometry_302: THREE.Mesh
    geometry_303: THREE.Mesh
    geometry_304: THREE.Mesh
    geometry_305: THREE.Mesh
    geometry_306: THREE.Mesh
    geometry_307: THREE.Mesh
    geometry_308: THREE.Mesh
    geometry_309: THREE.Mesh
    geometry_310: THREE.Mesh
    geometry_311: THREE.Mesh
    geometry_312: THREE.Mesh
    geometry_313: THREE.Mesh
    geometry_314: THREE.Mesh
    geometry_315: THREE.Mesh
    geometry_316: THREE.Mesh
    geometry_317: THREE.Mesh
    geometry_318: THREE.Mesh
    geometry_319: THREE.Mesh
    geometry_320: THREE.Mesh
    geometry_321: THREE.Mesh
    geometry_322: THREE.Mesh
    geometry_323: THREE.Mesh
    geometry_324: THREE.Mesh
    geometry_325: THREE.Mesh
    geometry_326: THREE.Mesh
    geometry_327: THREE.Mesh
    geometry_328: THREE.Mesh
    geometry_329: THREE.Mesh
    geometry_330: THREE.Mesh
    geometry_331: THREE.Mesh
    geometry_332: THREE.Mesh
    geometry_333: THREE.Mesh
    geometry_334: THREE.Mesh
    geometry_335: THREE.Mesh
    geometry_336: THREE.Mesh
    geometry_337: THREE.Mesh
    geometry_338: THREE.Mesh
    geometry_339: THREE.Mesh
    geometry_340: THREE.Mesh
    geometry_341: THREE.Mesh
    geometry_342: THREE.Mesh
    geometry_343: THREE.Mesh
    geometry_344: THREE.Mesh
    geometry_345: THREE.Mesh
    geometry_346: THREE.Mesh
    geometry_347: THREE.Mesh
    geometry_348: THREE.Mesh
    geometry_349: THREE.Mesh
    geometry_350: THREE.Mesh
    geometry_351: THREE.Mesh
    geometry_352: THREE.Mesh
    geometry_353: THREE.Mesh
    geometry_354: THREE.Mesh
    geometry_355: THREE.Mesh
    geometry_356: THREE.Mesh
    geometry_357: THREE.Mesh
    geometry_358: THREE.Mesh
    geometry_359: THREE.Mesh
    geometry_360: THREE.Mesh
    geometry_361: THREE.Mesh
    geometry_362: THREE.Mesh
    geometry_363: THREE.Mesh
    geometry_364: THREE.Mesh
    geometry_365: THREE.Mesh
    geometry_366: THREE.Mesh
    geometry_367: THREE.Mesh
    geometry_368: THREE.Mesh
    geometry_369: THREE.Mesh
    geometry_370: THREE.Mesh
    geometry_371: THREE.Mesh
    geometry_372: THREE.Mesh
    geometry_373: THREE.Mesh
    geometry_374: THREE.Mesh
    geometry_375: THREE.Mesh
    geometry_376: THREE.Mesh
    geometry_377: THREE.Mesh
    geometry_378: THREE.Mesh
    geometry_379: THREE.Mesh
    geometry_380: THREE.Mesh
    geometry_381: THREE.Mesh
    geometry_382: THREE.Mesh
    geometry_383: THREE.Mesh
    geometry_384: THREE.Mesh
    geometry_385: THREE.Mesh
    geometry_386: THREE.Mesh
    geometry_387: THREE.Mesh
    geometry_388: THREE.Mesh
    geometry_389: THREE.Mesh
    geometry_390: THREE.Mesh
    geometry_391: THREE.Mesh
    geometry_392: THREE.Mesh
    geometry_393: THREE.Mesh
    geometry_394: THREE.Mesh
    geometry_395: THREE.Mesh
    geometry_396: THREE.Mesh
    geometry_397: THREE.Mesh
    geometry_398: THREE.Mesh
    geometry_399: THREE.Mesh
    geometry_400: THREE.Mesh
    geometry_401: THREE.Mesh
    geometry_402: THREE.Mesh
    geometry_403: THREE.Mesh
    geometry_404: THREE.Mesh
    geometry_405: THREE.Mesh
    geometry_406: THREE.Mesh
    geometry_407: THREE.Mesh
    geometry_408: THREE.Mesh
    geometry_409: THREE.Mesh
    geometry_410: THREE.Mesh
    geometry_411: THREE.Mesh
    geometry_412: THREE.Mesh
    geometry_413: THREE.Mesh
    geometry_414: THREE.Mesh
    geometry_415: THREE.Mesh
    geometry_416: THREE.Mesh
    geometry_417: THREE.Mesh
    geometry_418: THREE.Mesh
    geometry_419: THREE.Mesh
    geometry_420: THREE.Mesh
    geometry_421: THREE.Mesh
    geometry_422: THREE.Mesh
    geometry_423: THREE.Mesh
    geometry_424: THREE.Mesh
    geometry_425: THREE.Mesh
    geometry_426: THREE.Mesh
    geometry_427: THREE.Mesh
    geometry_428: THREE.Mesh
    geometry_429: THREE.Mesh
    geometry_430: THREE.Mesh
    geometry_431: THREE.Mesh
    geometry_432: THREE.Mesh
    geometry_433: THREE.Mesh
    geometry_434: THREE.Mesh
    geometry_435: THREE.Mesh
    geometry_436: THREE.Mesh
    geometry_437: THREE.Mesh
    geometry_438: THREE.Mesh
    geometry_439: THREE.Mesh
    geometry_440: THREE.Mesh
    geometry_441: THREE.Mesh
    geometry_442: THREE.Mesh
    geometry_443: THREE.Mesh
    geometry_444: THREE.Mesh
    geometry_445: THREE.Mesh
    geometry_446: THREE.Mesh
    geometry_447: THREE.Mesh
  }
  materials: {
    ['Midnight Navy']: THREE.MeshStandardMaterial
    ['Soft Blue Floor']: THREE.MeshStandardMaterial
    ['Architectural White']: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Brushed Metal']: THREE.MeshStandardMaterial
    ['Soft Indigo']: THREE.MeshStandardMaterial
    ['Technical Dark']: THREE.MeshStandardMaterial
    ['Screen Glow']: THREE.MeshStandardMaterial
    ['Workbench Wood']: THREE.MeshStandardMaterial
    ['Deep Blue']: THREE.MeshStandardMaterial
    Skin_STEMStudent1: THREE.MeshStandardMaterial
    SkinArm_STEMStudent1: THREE.MeshStandardMaterial
    Skin_STEMStudent2: THREE.MeshStandardMaterial
    SkinArm_STEMStudent2: THREE.MeshStandardMaterial
    ['STEM Accent']: THREE.MeshStandardMaterial
    Skin_RobotStudent1: THREE.MeshStandardMaterial
    SkinArm_RobotStudent1: THREE.MeshStandardMaterial
    Skin_RobotStudent2: THREE.MeshStandardMaterial
    SkinArm_RobotStudent2: THREE.MeshStandardMaterial
    ['Circuit Green']: THREE.MeshStandardMaterial
    Skin_ElectronicsStudent1: THREE.MeshStandardMaterial
    SkinArm_ElectronicsStudent1: THREE.MeshStandardMaterial
    Skin_ElectronicsStudent2: THREE.MeshStandardMaterial
    SkinArm_ElectronicsStudent2: THREE.MeshStandardMaterial
    Skin_AstronomyStudent1: THREE.MeshStandardMaterial
    SkinArm_AstronomyStudent1: THREE.MeshStandardMaterial
    Skin_AstronomyStudent2: THREE.MeshStandardMaterial
    SkinArm_AstronomyStudent2: THREE.MeshStandardMaterial
    ['Safety Accent']: THREE.MeshStandardMaterial
    Skin_CompositeStudent1: THREE.MeshStandardMaterial
    SkinArm_CompositeStudent1: THREE.MeshStandardMaterial
    Skin_CompositeStudent2: THREE.MeshStandardMaterial
    SkinArm_CompositeStudent2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/gyantrika_innovation_hub.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.geometry_0.geometry} material={materials['Midnight Navy']} />
      <mesh geometry={nodes.geometry_1.geometry} material={materials['Soft Blue Floor']} />
      <mesh geometry={nodes.geometry_2.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_3.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_4.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_5.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_6.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_7.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_8.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_9.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_10.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_11.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_12.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_13.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_14.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_15.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_16.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_17.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_18.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_19.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_20.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_21.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_22.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_23.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_24.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_25.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_26.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_27.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_28.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_29.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_30.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_31.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_32.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_33.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_34.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_35.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_36.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_37.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_38.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_39.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_40.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_41.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_42.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_43.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_44.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_45.geometry} material={materials.Glass} />
      <mesh geometry={nodes.geometry_46.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_47.geometry} material={materials['Soft Indigo']} />
      <mesh geometry={nodes.geometry_48.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_49.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_50.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_51.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_52.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_53.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_54.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_55.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_56.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_57.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_58.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_59.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_60.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_61.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_62.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_63.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_64.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_65.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_66.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_67.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_68.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_69.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_70.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_71.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_72.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_73.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_74.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_75.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_76.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_77.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_78.geometry} material={materials['Workbench Wood']} />
      <mesh geometry={nodes.geometry_79.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_80.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_81.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_82.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_83.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_84.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_85.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_86.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_87.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_88.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_89.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_90.geometry} material={materials['Workbench Wood']} />
      <mesh geometry={nodes.geometry_91.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_92.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_93.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_94.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_95.geometry} material={materials['Workbench Wood']} />
      <mesh geometry={nodes.geometry_96.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_97.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_98.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_99.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_100.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_101.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_102.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_103.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_104.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_105.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_106.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_107.geometry} material={materials['Workbench Wood']} />
      <mesh geometry={nodes.geometry_108.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_109.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_110.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_111.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_112.geometry} material={materials['Workbench Wood']} />
      <mesh geometry={nodes.geometry_113.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_114.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_115.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_116.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_117.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_118.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_119.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_120.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_121.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_122.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_123.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_124.geometry} material={materials['Workbench Wood']} />
      <mesh geometry={nodes.geometry_125.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_126.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_127.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_128.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_129.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_130.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_131.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_132.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_133.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_134.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_135.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_136.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_137.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_138.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_139.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_140.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_141.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_142.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_143.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_144.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_145.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_146.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_147.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_148.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_149.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_150.geometry} material={materials.Skin_STEMStudent1} />
      <mesh geometry={nodes.geometry_151.geometry} material={materials.SkinArm_STEMStudent1} />
      <mesh geometry={nodes.geometry_152.geometry} material={materials.SkinArm_STEMStudent1} />
      <mesh geometry={nodes.geometry_153.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_154.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_155.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_156.geometry} material={materials.Skin_STEMStudent2} />
      <mesh geometry={nodes.geometry_157.geometry} material={materials.SkinArm_STEMStudent2} />
      <mesh geometry={nodes.geometry_158.geometry} material={materials.SkinArm_STEMStudent2} />
      <mesh geometry={nodes.geometry_159.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_160.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_161.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_162.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_163.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_164.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_165.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_166.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_167.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_168.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_169.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_170.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_171.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_172.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_173.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_174.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_175.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_176.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_177.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_178.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_179.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_180.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_181.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_182.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_183.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_184.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_185.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_186.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_187.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_188.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_189.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_190.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_191.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_192.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_193.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_194.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_195.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_196.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_197.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_198.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_199.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_200.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_201.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_202.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_203.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_204.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_205.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_206.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_207.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_208.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_209.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_210.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_211.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_212.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_213.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_214.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_215.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_216.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_217.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_218.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_219.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_220.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_221.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_222.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_223.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_224.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_225.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_226.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_227.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_228.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_229.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_230.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_231.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_232.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_233.geometry} material={materials.Skin_RobotStudent1} />
      <mesh geometry={nodes.geometry_234.geometry} material={materials.SkinArm_RobotStudent1} />
      <mesh geometry={nodes.geometry_235.geometry} material={materials.SkinArm_RobotStudent1} />
      <mesh geometry={nodes.geometry_236.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_237.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_238.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_239.geometry} material={materials.Skin_RobotStudent2} />
      <mesh geometry={nodes.geometry_240.geometry} material={materials.SkinArm_RobotStudent2} />
      <mesh geometry={nodes.geometry_241.geometry} material={materials.SkinArm_RobotStudent2} />
      <mesh geometry={nodes.geometry_242.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_243.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_244.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_245.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_246.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_247.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_248.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_249.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_250.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_251.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_252.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_253.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_254.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_255.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_256.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_257.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_258.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_259.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_260.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_261.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_262.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_263.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_264.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_265.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_266.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_267.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_268.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_269.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_270.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_271.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_272.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_273.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_274.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_275.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_276.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_277.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_278.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_279.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_280.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_281.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_282.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_283.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_284.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_285.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_286.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_287.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_288.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_289.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_290.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_291.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_292.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_293.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_294.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_295.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_296.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_297.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_298.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_299.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_300.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_301.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_302.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_303.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_304.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_305.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_306.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_307.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_308.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_309.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_310.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_311.geometry} material={materials.Skin_ElectronicsStudent1} />
      <mesh geometry={nodes.geometry_312.geometry} material={materials.SkinArm_ElectronicsStudent1} />
      <mesh geometry={nodes.geometry_313.geometry} material={materials.SkinArm_ElectronicsStudent1} />
      <mesh geometry={nodes.geometry_314.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_315.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_316.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_317.geometry} material={materials.Skin_ElectronicsStudent2} />
      <mesh geometry={nodes.geometry_318.geometry} material={materials.SkinArm_ElectronicsStudent2} />
      <mesh geometry={nodes.geometry_319.geometry} material={materials.SkinArm_ElectronicsStudent2} />
      <mesh geometry={nodes.geometry_320.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_321.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_322.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_323.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_324.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_325.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_326.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_327.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_328.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_329.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_330.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_331.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_332.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_333.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_334.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_335.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_336.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_337.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_338.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_339.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_340.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_341.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_342.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_343.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_344.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_345.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_346.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_347.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_348.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_349.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_350.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_351.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_352.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_353.geometry} material={materials['Screen Glow']} />
      <mesh geometry={nodes.geometry_354.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_355.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_356.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_357.geometry} material={materials.Skin_AstronomyStudent1} />
      <mesh geometry={nodes.geometry_358.geometry} material={materials.SkinArm_AstronomyStudent1} />
      <mesh geometry={nodes.geometry_359.geometry} material={materials.SkinArm_AstronomyStudent1} />
      <mesh geometry={nodes.geometry_360.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_361.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_362.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_363.geometry} material={materials.Skin_AstronomyStudent2} />
      <mesh geometry={nodes.geometry_364.geometry} material={materials.SkinArm_AstronomyStudent2} />
      <mesh geometry={nodes.geometry_365.geometry} material={materials.SkinArm_AstronomyStudent2} />
      <mesh geometry={nodes.geometry_366.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_367.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_368.geometry} material={materials['Workbench Wood']} />
      <mesh geometry={nodes.geometry_369.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_370.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_371.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_372.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_373.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_374.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_375.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_376.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_377.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_378.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_379.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_380.geometry} material={materials['Workbench Wood']} />
      <mesh geometry={nodes.geometry_381.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_382.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_383.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_384.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_385.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_386.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_387.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_388.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_389.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_390.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_391.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_392.geometry} material={materials['Workbench Wood']} />
      <mesh geometry={nodes.geometry_393.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_394.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_395.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_396.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_397.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_398.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_399.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_400.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_401.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_402.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_403.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_404.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_405.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_406.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_407.geometry} material={materials['Safety Accent']} />
      <mesh geometry={nodes.geometry_408.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_409.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_410.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_411.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_412.geometry} material={materials['Safety Accent']} />
      <mesh geometry={nodes.geometry_413.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_414.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_415.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_416.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_417.geometry} material={materials['Safety Accent']} />
      <mesh geometry={nodes.geometry_418.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_419.geometry} material={materials['Safety Accent']} />
      <mesh geometry={nodes.geometry_420.geometry} material={materials['STEM Accent']} />
      <mesh geometry={nodes.geometry_421.geometry} material={materials['Circuit Green']} />
      <mesh geometry={nodes.geometry_422.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_423.geometry} material={materials['Midnight Navy']} />
      <mesh geometry={nodes.geometry_424.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_425.geometry} material={materials.Skin_CompositeStudent1} />
      <mesh geometry={nodes.geometry_426.geometry} material={materials.SkinArm_CompositeStudent1} />
      <mesh geometry={nodes.geometry_427.geometry} material={materials.SkinArm_CompositeStudent1} />
      <mesh geometry={nodes.geometry_428.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_429.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_430.geometry} material={materials['Deep Blue']} />
      <mesh geometry={nodes.geometry_431.geometry} material={materials.Skin_CompositeStudent2} />
      <mesh geometry={nodes.geometry_432.geometry} material={materials.SkinArm_CompositeStudent2} />
      <mesh geometry={nodes.geometry_433.geometry} material={materials.SkinArm_CompositeStudent2} />
      <mesh geometry={nodes.geometry_434.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_435.geometry} material={materials['Technical Dark']} />
      <mesh geometry={nodes.geometry_436.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_437.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_438.geometry} material={materials['Architectural White']} />
      <mesh geometry={nodes.geometry_439.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_440.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_441.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_442.geometry} material={materials['Brushed Metal']} />
      <mesh geometry={nodes.geometry_443.geometry} material={materials['Midnight Navy']} />
      <mesh geometry={nodes.geometry_444.geometry} material={materials['Midnight Navy']} />
      <mesh geometry={nodes.geometry_445.geometry} material={materials['Midnight Navy']} />
      <mesh geometry={nodes.geometry_446.geometry} material={materials['Midnight Navy']} />
      <mesh geometry={nodes.geometry_447.geometry} material={materials['Midnight Navy']} />
    </group>
  )
}

useGLTF.preload('/gyantrika_innovation_hub.glb')
